server:
  port: 9090

spring:
  application:
    name: marked_blog
  datasource:
    url: jdbc:mysql://106.15.184.199:3306/marked_blog
    username: mark
    password: 6nWZrKF7Cc7ZpP5D
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 5MB
  redis:
    host: 106.15.184.199
    port: 36220
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: marked_
  mapper-locations: classpath:mapper/*.xml

